sudo: false
dist: trusty

language: php

notifications:
    email:
        on_success: never
        on_failure: change

branches:
    only:
        - master

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    include:
        - php: 7.2
          env: WP_VERSION=latest
        - php: 7.0
          env: WP_VERSION=latest

before_script:
    - |
        if [[ ! -z "$WP_VERSION" ]] ; then
          cp .env.travis .env
          composer install
          composer install-wp-tests
        fi

script:
    - |
        if [[ ! -z "$WP_VERSION" ]] ; then
          php vendor/bin/codecept run wpunit
        fi
